# Generated by Django 4.0.6 on 2022-09-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeemail',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
