# Generated by Django 4.0.6 on 2022-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_email', '0002_resumeemail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeemail',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
